[package]
name = "itsfrank/frktest"
description = "Simple testing framework"
version = "0.0.2"
license = "MIT"
authors = ["Francis O'Brien <github.com/itsfrank>"]
registry = "https://github.com/upliftgames/wally-index"
# not really relevant here since this is intended for lune...
realm = "shared"

[dependencies]
